### ISSUE TITLE
[PVE9] - Unable to locate package neofetch

### ISSUE THREAD

**Issue by X1pheR** [BassT23/Proxmox#213]
**Describe the bug**
Getting an error during install that neofetch package cannot be located. See screenshot.

**To Reproduce**
1. Update to PVE9.
2. Install ultimate updater.

**Expected behavior**
No error would be shown.

**Screenshots**
<img width="1498" height="1364" alt="Image" src="https://github.com/user-attachments/assets/2a7dc269-2444-4785-89f3-db3915a02626" />

**VM/LXC (please complete the following information):**
 - OS: Proxmox VE (single node)
 - Version: 9

**Used Version**
Last modification (on GitHub): 2025-08-11T17:01:34Z

  Version overview
  Updater: 4.4
  Extras:  2.0
  Config:  1.8
  Welcome: 1.6
  Check:   1.7

**Additional context**
By googling I found that neofetch does not exist in debian anymore, since trixie. I installed fastfetch which works but don't know what the ultimate updater used neofetch for.

**Comment by BassT23** [comment]
> Take a look at https://github.com/fastfetch-cli/fastfetch as well. My understanding is that it's faster and has fewer dependencies. Just a suggestion, nothing more.

Done ;)

**Comment by BassT23** [comment]
ok, found some problems here:

- neofetch is no more possible on deb13
- fastfetch is not available on deb12
- also fastfetch seems like have color problems by binding it to welcome message (no color)

so i desidet to use screenfetch. It is available in deb 12 and 13, it is also small and work :)

**Comment by BassT23** [comment]
the checge is only in beta for now, so if you make a `update beta -up` it should install fastfetch.

beta is nearly stable, so far

**Comment by silmaril464** [comment]
I tried it this afternoon, but it still didn’t show me the welcome screen with all the information. I’ll try again tomorrow; maybe I did something wrong…
thx

**Comment by silmaril464** [comment]
Hi, I did a fresh installation of Proxmox 9, updated everything, and then installed the script through the host shell with

bash <(curl -s https://raw.githubusercontent.com/BassT23/Proxmox/master/install.sh)


when I saw that it wasn’t possible to install neofetch. Then I found this thread and saw what the problem was, so I ran update -up but it was still the same.

Today I saw you talking about the integration of screenfetch, and that’s when I decided to post about this. Afterwards, I decided to try the beta just in case by running update beta -up, then refreshed the Proxmox web interface and entered the shell, but it was still the same, not showing me the welcome screen with the data.

So I decided to uninstall the script and reinstall it, and that’s where I am now. Tomorrow I’ll try running update beta -up again to see if I notice any change.
Thanks a lot for your help :)

**Comment by silmaril464** [comment]
But that’s what I did this afternoon using the command `update beta -up` and I didn’t see any change.
sorry for my bad english

**Comment by silmaril464** [comment]
Wow, that was fast! Okay, take your time, I’ll follow your work closely to keep up with the updates about this. Thanks again for your help!
